NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3
INVALID = -1

MAX_SEARCH = 1000   # maximum number of visit at MCTS

INPUT_AREA_SIZE = 11
INPUT_CHANNELS = 98

NORMAL_MODEL_CHANNELS = 64
NORMAL_MODEL_BLOCKS = 8

SMALL_MODEL_CHANNELS = 48
SMALL_MODEL_BLOCKS = 8

TINY_MODEL_CHANNELS = 32
TINY_MODEL_BLOCKS = 8
